import { InterviewQuestion } from "./types";

export const soulQuestions: InterviewQuestion[] = [
  {
    id: "origin",
    section: "Your Story",
    question: "What's the defining experience that shaped how you do business today?",
    placeholder: "There was a moment when I realized that...",
    helpText: "Not your resume — the turning point. The lesson that changed everything after.",
    required: true,
  },
  {
    id: "expertise",
    section: "Your Expertise",
    question: "What do you know — from decades of experience — that most people in your industry still get wrong?",
    placeholder: "Everyone assumes... but after 20+ years I've learned that...",
    helpText: "This is your hard-won wisdom. The thing you wish someone had told you on day one.",
    required: true,
  },
  {
    id: "framework",
    section: "Your Framework",
    question: "What's your approach or method? The way YOU do things that gets results?",
    placeholder: "My approach is... I always start with... then...",
    helpText: "You may not have named it, but you have a system. Walk us through how you think about solving problems.",
    required: true,
  },
  {
    id: "anti_position",
    section: "What You Stand Against",
    question: "What common practice in your industry do you refuse to follow — and why?",
    placeholder: "I'll never... because I've seen what happens when...",
    helpText: "Your anti-positions define you as much as your beliefs. What do you push back on?",
    required: true,
  },
  {
    id: "legacy",
    section: "Your Legacy",
    question: "If you stepped away tomorrow, what knowledge would be hardest to replace?",
    placeholder: "The things only I know are... Nobody else understands...",
    helpText: "This is the institutional knowledge we're here to capture and preserve.",
    required: true,
  },
  {
    id: "principles",
    section: "Your Principles",
    question: "What are the 3-5 principles you operate by? The rules you'd never break?",
    placeholder: "1. Always... 2. Never... 3...",
    helpText: "These guide every decision. They're what make your business distinctly yours.",
    required: true,
  },
  {
    id: "vision",
    section: "Where You're Headed",
    question: "What does the next chapter look like? What are you building toward?",
    placeholder: "In the next 3-5 years, I want to...",
    helpText: "This helps AI understand your direction, not just your history.",
    required: false,
  },
];

export const offerQuestions: InterviewQuestion[] = [
  {
    id: "offer_name",
    section: "What You Do",
    question: "In one sentence, what do you do for your clients?",
    placeholder: "I help [type of person] achieve [specific outcome] by...",
    helpText: "The clearest version. What you'd say if someone asked at dinner.",
    required: true,
  },
  {
    id: "offer_outcome",
    section: "The Transformation",
    question: "What changes for your clients after working with you? Be specific.",
    placeholder: "Before: they were dealing with... After: they now have...",
    helpText: "Real results from real clients. Numbers, outcomes, changes you've seen firsthand.",
    required: true,
  },
  {
    id: "offer_process",
    section: "Your Process",
    question: "Walk us through how you work with a client, from start to finish.",
    placeholder: "First we... then... the final step is...",
    helpText: "Your delivery process. How does someone go from 'yes' to 'result'?",
    required: true,
  },
  {
    id: "offer_audience",
    section: "Your Best Client",
    question: "Describe the client who gets the MOST value from you. Who are they?",
    placeholder: "They're typically a... who has... and needs...",
    helpText: "Think of the client you wish you could clone. What makes them ideal?",
    required: true,
  },
  {
    id: "offer_differentiator",
    section: "Why You, Not Someone Else",
    question: "When a client chooses you over alternatives, what's the real reason?",
    placeholder: "They choose me because... Unlike others, I...",
    helpText: "Not features. The deeper reason — trust, experience, approach, results.",
    required: true,
  },
  {
    id: "offer_proof",
    section: "Your Best Case Study",
    question: "Tell us about a client win you're proud of. What happened?",
    placeholder: "We worked with... They were struggling with... We did... The result was...",
    helpText: "One specific story. This becomes proof that AI can reference in everything it generates.",
    required: false,
  },
];

export const audienceQuestions: InterviewQuestion[] = [
  {
    id: "audience_who",
    section: "Who You Serve",
    question: "Describe the person you do your best work for. Who are they, really?",
    placeholder: "They're a... who has spent years building... and they're at the point where...",
    helpText: "Not demographics. The real person — their role, their experience level, what drives them.",
    required: true,
  },
  {
    id: "audience_pain",
    section: "Their Real Problem",
    question: "What's the problem they can't solve on their own — even though they're smart and experienced?",
    placeholder: "They know they need to... but they can't because...",
    helpText: "The problem that brought them to you. Not surface-level — the thing that actually keeps them stuck.",
    required: true,
  },
  {
    id: "audience_tried",
    section: "What Hasn't Worked",
    question: "What have they already tried? What solutions left them frustrated?",
    placeholder: "They've tried... They've hired... They've spent money on...",
    helpText: "This tells AI what NOT to recommend and shows you understand their journey.",
    required: true,
  },
  {
    id: "audience_language",
    section: "How They Talk About It",
    question: "When they describe their problem to a trusted friend, what do they actually say?",
    placeholder: "\"I'm tired of...\" \"I just need someone who...\" \"Why can't I find...\"",
    helpText: "Their words, not yours. This is how AI learns to speak directly to them.",
    required: true,
  },
  {
    id: "audience_stakes",
    section: "What's At Stake",
    question: "What happens if they DON'T solve this? What's the cost of doing nothing?",
    placeholder: "If they don't act, they'll... The risk is...",
    helpText: "This isn't about fear. It's about making the urgency real — for them and for AI.",
    required: true,
  },
];

export const voiceQuestions: InterviewQuestion[] = [
  {
    id: "voice_tone",
    section: "How You Come Across",
    question: "When you're at your best — in a meeting, on a call, writing an email — how do people experience you?",
    placeholder: "People say I'm... My style is...",
    helpText: "Not how you want to sound. How you actually sound when you're in your element.",
    required: true,
  },
  {
    id: "voice_phrases",
    section: "Things You Always Say",
    question: "What phrases, analogies, or expressions do you use over and over?",
    placeholder: "I always tell people... My go-to analogy is... I tend to say...",
    helpText: "These are your verbal fingerprints. The things your team or clients could quote back to you.",
    required: true,
  },
  {
    id: "voice_never",
    section: "What You'd Never Say",
    question: "What words, phrases, or styles make you cringe? What's NOT you?",
    placeholder: "I'd never say... It sounds too... I can't stand when people...",
    helpText: "Just as important as what you do say. This keeps AI from making you sound generic.",
    required: true,
  },
  {
    id: "voice_example",
    section: "Your Natural Voice",
    question: "Write a few sentences about what you do — the way you'd actually explain it to someone you respect.",
    placeholder: "Here's how I see it...",
    helpText: "Don't perform. Just talk. This is how AI learns the real you.",
    required: true,
  },
  {
    id: "voice_influence",
    section: "Who Shaped Your Style",
    question: "Whose communication style do you admire? Who do you sound like — or want to?",
    placeholder: "I've always admired how [person] communicates because...",
    helpText: "A mentor, a leader, an author. This gives AI a reference point for your tone.",
    required: false,
  },
];
