import { InterviewQuestion } from "./types";

export const soulQuestions: InterviewQuestion[] = [
  {
    id: "origin",
    section: "Origin Story",
    question: "What made you start this business? What moment or frustration pushed you to do this?",
    placeholder: "I was working at... and I realized that...",
    helpText: "The real story, not the polished version. What actually happened.",
    required: true,
  },
  {
    id: "problem",
    section: "The Problem You Solve",
    question: "What problem do your clients have that keeps them up at night?",
    placeholder: "They're struggling with... and it makes them feel...",
    helpText: "Describe it the way your clients would say it, not how a marketer would write it.",
    required: true,
  },
  {
    id: "belief",
    section: "Core Belief",
    question: "What do you believe about your industry that most people get wrong?",
    placeholder: "Most people think... but the truth is...",
    helpText: "This is your contrarian edge. What do you know that others don't?",
    required: true,
  },
  {
    id: "transformation",
    section: "The Transformation",
    question: "When a client succeeds with you, what does their life look like after?",
    placeholder: "They go from... to...",
    helpText: "Paint the before and after. Be specific — what changes day-to-day?",
    required: true,
  },
  {
    id: "why_you",
    section: "Why You",
    question: "Why are YOU the right person to solve this? What's your unfair advantage?",
    placeholder: "I've spent X years... I've personally...",
    helpText: "This isn't about credentials. It's about lived experience.",
    required: true,
  },
  {
    id: "values",
    section: "Non-Negotiables",
    question: "What will you NEVER do in your business, no matter what?",
    placeholder: "I will never... because...",
    helpText: "These are your lines in the sand. What separates you from the people you don't want to be?",
    required: true,
  },
  {
    id: "mission",
    section: "The Mission",
    question: "If your business succeeds beyond your wildest dreams, what changes in the world?",
    placeholder: "More people would... The industry would...",
    helpText: "Think bigger than revenue. What's the ripple effect?",
    required: false,
  },
];

export const offerQuestions: InterviewQuestion[] = [
  {
    id: "offer_name",
    section: "The Offer",
    question: "What do you sell? Give it a name and describe it in one sentence.",
    placeholder: "It's called... and it helps people...",
    helpText: "If you had 10 seconds in an elevator, what would you say?",
    required: true,
  },
  {
    id: "offer_outcome",
    section: "The Outcome",
    question: "What specific result does someone get from buying this?",
    placeholder: "In X weeks/months, they will...",
    helpText: "Be concrete. 'Feel better' is weak. 'Land 3 new clients' is strong.",
    required: true,
  },
  {
    id: "offer_price",
    section: "Price & Model",
    question: "How much does it cost and how is it delivered?",
    placeholder: "$X per month / one-time. Delivered via...",
    helpText: "Include the delivery method — 1:1, group, course, community, etc.",
    required: true,
  },
  {
    id: "offer_audience",
    section: "Who It's For",
    question: "Describe the PERFECT buyer in one sentence. Who gets the most value?",
    placeholder: "This is for someone who...",
    helpText: "Not everyone. The specific person who's ready and needs this NOW.",
    required: true,
  },
  {
    id: "offer_differentiator",
    section: "Why This vs. Alternatives",
    question: "What makes your offer different from the 10 other options they could choose?",
    placeholder: "Unlike [competitors], we...",
    helpText: "If the answer is 'nothing,' that's the real problem to solve.",
    required: true,
  },
];

export const audienceQuestions: InterviewQuestion[] = [
  {
    id: "audience_who",
    section: "Who They Are",
    question: "Who is your ideal client? Describe them as a real person, not a demographic.",
    placeholder: "They're a... who has been... and they're at the point where...",
    helpText: "Think of your best client ever. Describe that person.",
    required: true,
  },
  {
    id: "audience_struggle",
    section: "What They're Struggling With",
    question: "What are they dealing with right now that brought them to you?",
    placeholder: "They're stuck because... Every day they...",
    helpText: "Use their words, not industry jargon. What do they say when they vent to a friend?",
    required: true,
  },
  {
    id: "audience_tried",
    section: "What They've Already Tried",
    question: "What have they already tried that didn't work?",
    placeholder: "They've tried... They've paid for... They've spent time on...",
    helpText: "This is important — it tells AI what NOT to suggest and shows you understand their frustration.",
    required: true,
  },
  {
    id: "audience_desire",
    section: "What They Actually Want",
    question: "In their own words, what do they wish they had?",
    placeholder: "\"I just want...\" \"If only I could...\"",
    helpText: "Not what you think they need — what THEY say they want. The gap between these two is your positioning.",
    required: true,
  },
  {
    id: "audience_objection",
    section: "Why They Hesitate",
    question: "What's the main reason they don't buy, even when they want to?",
    placeholder: "They worry that... They're not sure if...",
    helpText: "The real objection, not the polite one. What's actually stopping them?",
    required: true,
  },
];

export const voiceQuestions: InterviewQuestion[] = [
  {
    id: "voice_tone",
    section: "Your Tone",
    question: "How would you describe your tone in 2-3 words?",
    placeholder: "Direct and warm... Professional but casual... Blunt but caring...",
    helpText: "Think about how a friend would describe the way you talk about your work.",
    required: true,
  },
  {
    id: "voice_phrases",
    section: "Signature Phrases",
    question: "What phrases or words do you use a lot? What's distinctly 'you'?",
    placeholder: "I always say... My go-to words are... I tend to open with...",
    helpText: "These are the verbal fingerprints that make your content sound like YOU wrote it.",
    required: true,
  },
  {
    id: "voice_never",
    section: "Words You'd Never Use",
    question: "What words or phrases would you NEVER say? What makes you cringe?",
    placeholder: "I'd never say... It sounds too... I hate when people use...",
    helpText: "This is just as important as what you do say. It keeps AI from making you sound like everyone else.",
    required: true,
  },
  {
    id: "voice_example",
    section: "Write Like You Talk",
    question: "Write a short paragraph about your work — the way you'd actually say it to a friend.",
    placeholder: "Here's the thing about...",
    helpText: "Don't try to sound smart or polished. Just talk. This is how AI learns your real voice.",
    required: true,
  },
  {
    id: "voice_personality",
    section: "Your Personality",
    question: "What's your personality like when you're at your best? How do you show up?",
    placeholder: "I'm the kind of person who... When I'm in my zone I...",
    helpText: "Are you the calm one? The intense one? The funny one? The straight-shooter? AI needs to know.",
    required: true,
  },
];
